### ISSUE TITLE
KNX does not work in iOS 11

### ISSUE THREAD

**Issue by zork17** [snowdd1/homebridge-knx#104]
I have 2 homebridge instances.
The first one has only KNX with 96 devices and the second is with all the other plugins.
After upgrade to iOS 11, it worked for a short time.
Now, after a few hours, the second homebridge instance with all the other plugins is working, but the most important plugin - KNX - does not work.
There are no errors in the log, 
I see only the following lines every now and then:
```
Sep 20 23:16:57 RSBPI homebridge[550]: [9/20/2017, 11:16:57 PM] [KNX] Value changed, updating homebridge
Sep 20 23:16:57 RSBPI homebridge[550]: [9/20/2017, 11:16:57 PM] [KNX] exiting writeValueHK()
Sep 20 23:16:57 RSBPI homebridge[550]: [9/20/2017, 11:16:57 PM] [KNX] Value changed, updating homebridge
Sep 20 23:16:57 RSBPI homebridge[550]: [9/20/2017, 11:16:57 PM] [KNX] exiting writeValueHK()
Sep 20 23:16:57 RSBPI homebridge[550]: [9/20/2017, 11:16:57 PM] [KNX] Value changed, updating homebridge
Sep 20 23:16:57 RSBPI homebridge[550]: [9/20/2017, 11:16:57 PM] [KNX] exiting writeValueHK()
Sep 20 23:16:57 RSBPI homebridge[550]: [9/20/2017, 11:16:57 PM] [KNX] Value changed, updating homebridge
Sep 20 23:16:57 RSBPI homebridge[550]: [9/20/2017, 11:16:57 PM] [KNX] exiting writeValueHK()
```
In the Apple Home app I see No Response in red for all the KNX devices (and also for homebridge).
I have the latest versions.

Everything worked great for many months...
What can I do?

**Comment by hyperbart** [comment]
Upgrade your Apple TV, very bizarre but that also seems to impact your local functionality...

**Comment by snowdd1** [comment]
I needed to unbind homebridge from Homekit and pair it again to get access again (using an iPad a central, not an ATV4). Homebridge somehow thought homebridge to be a malicious piece of hardware.

**Comment by zork17** [comment]
What do you mean by unbinding?
I also have an ipad and not ATV4. 
I ended up deleting the folders and changing the username and removing and adding the Knx homebridge again. 
The big problem is I had to enter most of the rules and scenes again. 
The other homebridge service continued to work all the time. 
As I said before, this knx only homebridge worked at the beginning for a few hours and then stopped. 
Is there a quicker way to solve this in the future?

**Comment by snowdd1** [comment]
errr, by unbinding I meant exactly that. I removed homebridge from the home, and then deleted persist and accessories folders.

Since I do not know what went wrong in the first place, I do not have a suggestion for you.

I now used a split installation, running 5 instances (4 floors of KNX and one for TPLINK hs100 and probably others in the future). To do that, I did some minor enhancements to homebridge-knx, such as making the web server port configurable to allow multiple instances on one machine. [See here](https://github.com/snowdd1/homebridge-knx/releases/tag/v0.3.12)

**Comment by bbdj-dev** [comment]
I have the same problem, after updating the Ipad it’s work for a short time and then stop working, sometimes resumes working sometimes I‘ve to to turn off the ipad and reboot the raspberry to get it started working again.

**Comment by snowdd1** [comment]
My homebridge now ran stable for four weeks. I just updated knxd from v0.12 to v0.14, that didn't break anything either.

I split the installation into 5 instances, hoping to gain reaction speed in Home App and in the Home Watch app, which simply didn't happen. So it seams no matter if you have 70+ accessories in one bridge or distributed over 4 bridges.

**Comment by bbdj-dev** [comment]
I think taht the problem is into HomeKit... I’ve KNXD 0.14 and after re-configuring Homebridge and HomeKit the system worked fine for two weeks and than stopped working again (HomeKit could no longer update the devices), I disconnected HomeKit from all devices (iPhone and Ipad) for 1 hour and after it has started working again.
