### ISSUE TITLE
knxd 

### ISSUE THREAD

**Issue by reejinbouk** [snowdd1/homebridge-knx#31]
Hi, Raoul!
Please, tell me, which version of knxd server is more stable and better to use?
Thank YOU

**Comment by snowdd1** [comment]
I personally use the master branch as of February this year, together with a busware pigator module for physical access (see https://github.com/knxd/knxd/wiki/Adding-a-busware-pigator-KNX-TPUART-(Raspberry) )
The conn_sep branch had a few issues then. However, I haven't tested or changed anything since then. Programming works with my ets4 via knxd. I have read from others that programming devices using ets5 might be an issue with knxd.
Good look!
