### ISSUE TITLE
Structure of knx_config.json in 0.3

### ISSUE THREAD

**Issue by matevzg** [snowdd1/homebridge-knx#83]
Hey @snowdd1, what do you propose?

- defining multiple services/device?
   - i.e Living Room [Device] with Ceiling Light [Service], LED Strip [Service], ...
- defining multiple single service devices?
   - i.e. Living Room Ceiling Light [Device] with Living Room Ceiling Light [Service]
   - i.e. Living Room LED Strip [Device] with Living Room LED Strip [Service]
   - ...

What influence/benefits does it have for Siri regarding naming? Any other possible issues?

I'm asking because in 0.2, I designed multiple services/accessory and it worked like a charm. You would be able to move a Living Room accessory into the Living Room [Room] and all lights/blinds/thermostats/sensors would be transferred with it in one go. It seems HomeKit only displays services as icons within the Home app anyway.

Thanks for your insight.

**Comment by snowdd1** [comment]
Hello @matevzg ,
you are right. Especially as Homekit has an 100-accessories-per-bridge limit, I recommend bundling services by room.  
In my private installation, I have bundled
- Lights
- Heating (actually only temperature sensors, heating is time controlled)
- Window contacts
- Blinds  

per room. Most HomeKit apps do not show the accessory/device names any more, since Apple's **Home** app has completely ignored them (Actually, in the background it still uses accessory-to-room assignment API).

**Comment by matevzg** [comment]
OK, perfect. In this case knx_config.json sample should be modified accordingly. Currently it implies that multiple single service devices should be defined. Even a mention about this in documentation would suffice.

Thanks again.

**Comment by snowdd1** [comment]
Example adjusted: https://github.com/snowdd1/homebridge-knx/blob/master/knx_config.json.md#example
